<?php

/**
 * @file
 * This module allows to display the modules weight on the Modules page.
 */


/**
 * Implements hook_menu().
 */
function tweaks_modules_weight_menu() {

  $items['admin/config/tweaks/modules-weight'] = array(
    'title' => 'Modules weight',
    'description' => 'Allows to display the modules weight on the Modules page.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('tweaks_modules_weight_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'tweaks_modules_weight.admin.inc',
  );

  return $items;
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function tweaks_modules_weight_form_system_modules_alter(&$form, &$form_state, $form_id) {

  $modules_weight = config_get('tweaks_modules_weight.settings', 'modules_weight');

  if ($modules_weight == 'display') {

    $modules = system_rebuild_module_data();

    foreach (element_children($form['modules']) as $package) {

      // Add weight data to each enabled module.
      foreach (element_children($form['modules'][$package]) as $module) {
        $form['modules'][$package][$module]['weight'] = array(
          '#markup' => !!$modules[$module]->status ? $modules[$module]->weight : '',
        );
      }

      // Replace theme implementation.
      $form['modules'][$package]['#theme'] = 'tweaks_modules_weight_system_modules_fieldset';

      // Add weight column to table header.
      $header = $form['modules'][$package]['#header'];
      $form['modules'][$package]['#header'] = array_merge(
        array_slice($header, 0, 3),
        array(array('data' => t('Weight'), 'class' => array(RESPONSIVE_PRIORITY_MEDIUM))),
        array_slice($header, 3)
      );
    }
  }
}


/**
 * Implements hook_theme().
 */
function tweaks_modules_weight_theme() {

  $themes['tweaks_modules_weight_system_modules_fieldset'] = array(
    'render element' => 'form',
    'file' => 'tweaks_modules_weight.theme.inc',
  );

  return $themes;
}


/**
 * Implements hook_config_info().
 */
function tweaks_modules_weight_config_info() {

  $prefixes['tweaks_modules_weight.settings'] = array(
    'label' => t('Modules Weight settings'),
    'group' => t('Tweaks'),
  );

  return $prefixes;
}
