<?php

/**
 * @file
 * Allows to set a maximum age of log messages to keep in the database log.
 */


/**
 * Implements hook_menu().
 */
function tweaks_log_messages_menu() {

  $items['admin/config/tweaks/log-messages'] = array(
    'title' => 'Log messages',
    'description' => 'Allows to set a maximum age of log messages to keep in the database log.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('tweaks_log_messages_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'tweaks_log_messages.admin.inc',
  );

  return $items;
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function tweaks_log_messages_form_dblog_clear_log_form_alter(&$form, &$form_state, $form_id) {

  if (!config_get('tweaks_log_messages.settings', 'clear_log_form')) {

    $form['#access'] = FALSE;
  }
}


/**
 * Implements hook_cron().
 */
function tweaks_log_messages_cron() {

  $dblog_row_age = config_get('tweaks_log_messages.settings', 'dblog_row_age');

  if ($dblog_row_age > 0) {

    db_delete('watchdog')
      ->condition('timestamp', REQUEST_TIME - $dblog_row_age, '<')
      ->execute();
  }
}


/**
 * Implements hook_config_info().
 */
function tweaks_log_messages_config_info() {

  $prefixes['tweaks_log_messages.settings'] = array(
    'label' => t('Log Messages settings'),
    'group' => t('Tweaks'),
  );

  return $prefixes;
}
